function clean(value: unknown): string {
  return String(value ?? "")
    .replace(/&lt;br&gt;/g, " ")
    .replace(/<br\s*\/?>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function pick(raw: Record<string, unknown>, keys: string[]): string {
  for (const key of keys) {
    const value = clean(raw[key]);
    if (value) return value;
  }
  return "";
}

function joinParts(parts: string[], sep = " / "): string {
  return parts.filter(Boolean).join(sep);
}

export function buildMemo(raw: Record<string, unknown>): string {
  const playerName = pick(raw, ["playerName", "pl", "PL"]);
  const level = pick(raw, ["level", "CL", "cl"]);
  const classMain = pick(raw, ["classMain"]);
  const classSupport = pick(raw, ["classSupport"]);
  const classTitle = pick(raw, ["classTitle", "classTitleClass"]);
  const age = pick(raw, ["age", "characterAge"]);
  const gender = pick(raw, ["gender", "sex"]);
  const race = pick(raw, ["race"]);
  const origin = pick(raw, ["lifepathOrigin"]);
  const experience = pick(raw, ["lifepathExperience"]);
  const motive = pick(raw, ["lifepathMotive"]);
  const guild = pick(raw, ["guildName"]);

  const blocks: string[] = [];
  const header: string[] = [];
  if (playerName) header.push(`PL：${playerName}`);
  if (level) header.push(`CL：${level}`);
  const classes = joinParts([classMain, classSupport, classTitle]);
  if (classes) header.push(classes);
  if (header.length) blocks.push(header.join("\n"));

  const profile: string[] = [];
  const ageGenderRace = joinParts([age ? `${age}歳` : "", gender, race]);
  if (ageGenderRace) profile.push(ageGenderRace);
  const lifepath = joinParts([
    origin ? `出自：${origin}` : "",
    experience ? `境遇：${experience}` : "",
    motive ? `目的：${motive}` : "",
  ]);
  if (lifepath) profile.push(lifepath);
  if (profile.length) blocks.push(profile.join("\n"));

  if (guild) blocks.push(`ギルド：${guild}`);

  return blocks.join("\n\n") || "Generated by ytsheet2 converter";
}
