export function buildCharacterJson(name: string, externalUrl: string, status: unknown[], params: unknown[], commands: string) {
  return { kind: "character", data: { name, initiative: 0, externalUrl, memo: "Generated by ytsheet2 converter", status, params, commands } };
}
