export function buildCharacterJson(name: string, externalUrl: string, status: unknown[], params: unknown[], commands: string, initiative = 0, memo = "Generated by ytsheet2 converter") {
  return { kind: "character", data: { name, initiative, externalUrl, memo, status, params, commands } };
}
