export function buildCharacterJson(name: string, externalUrl: string, status: unknown[], params: unknown[], commands: string, initiative = 0) {
  return { kind: "character", data: { name, initiative, externalUrl, memo: "Generated by ytsheet2 converter", status, params, commands } };
}
